version: "1.0"
services:
  geth:
    image: "emird/geth_from_source:latest"
    networks:
      ETHclient_net:
        ipv4_address: 172.19.0.7
    command:
      - --netrestrict=172.19.0.0/16
      - --networkid=32382
      - --http
      - --http.api=eth
      - --http.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.jwtsecret=/execution/jwtsecret
      - --bootnodes=${EL_BOOTNODE}
      - --datadir=/execution
      - --allow-insecure-unlock
      - --unlock=0x123463a4b065722e99115d6c222f267d9cabb524
      - --password=/execution/geth_password.txt
      - --syncmode=full
    expose:
      - 8551:8551
      - 8545:8545
      - 6060:6060
      - 30303:30303
    volumes:
      - ./execution:/execution
      - ./execution/geth_password.txt:/execution/geth_password.txt
      - ./jwtsecret:/execution/jwtsecret

  # Runs a Prysm beacon chain from a specified genesis state created in the previous step
  # and connects to go-ethereum in the same network as the execution client.
  # The account used in go-ethereum is set as the suggested fee recipient for transactions
  # proposed via the validators attached to the beacon node.
  beacon-chain:
    image: "emird/prysm_bc_source:latest"
    networks:
      ETHclient_net:
        ipv4_address: 172.19.0.8
    command:
      - --slasher
      - --datadir=/consensus/beacondata
      # No peers to sync with in this testnet, so setting to 0
      - --min-sync-peers=0
      - --genesis-state=/consensus/genesis.ssz
      - --bootstrap-node=${CL_BOOTNODE}
      # The chain configuration file used for setting up Prysm
      - --chain-config-file=/consensus/config.yml
      # We specify the chain id used by our execution client
      - --chain-id=32382
      - --contract-deployment-block=0
      - --execution-endpoint=http://172.19.0.7:8551
      - --rpc-host=0.0.0.0
      - --accept-terms-of-use
      - --jwt-secret=/execution/jwtsecret
      - --suggested-fee-recipient=0x123463a4b065722e99115d6c222f267d9cabb524
    depends_on:
      geth:
        condition: service_started
    expose:
      - 4000:4000
      - 3500:3500
      - 8080:8080
      - 8081:8081
      - 12000:12000
      - 13000:13000
    volumes:
      - ./consensus:/consensus
      - ./jwtsecret:/execution/jwtsecret

networks:
  ETHclient_net:
    name: ETHclient_net
    external: true
    ipam:
        driver: default
        config:
            - subnet: "172.19.0.0/16"