version: "1.0"
services:
  geth:
    image: "ethereum/client-go:latest"
    networks:
      ETHclient_net:
        ipv4_address: 172.19.0.11
    command:
      - --http
      - --http.api=eth,net,web3
      - --http.addr=0.0.0.0
      - --netrestrict=172.19.0.0/16
      - --ethstats=node2:2e0834786285daccd064ca17f1654f67b4aef298acbb82cef9ec422fb4975622@127.0.0.1:30303
      - --networkid=32382
      - --authrpc.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.jwtsecret=/execution/jwtsecret
      - --bootnodes=${EL_BOOTNODE}
      - --datadir=/execution
      - --allow-insecure-unlock
      - --unlock=0x123463a4b065722e99115d6c222f267d9cabb524
      - --password=/execution/geth_password.txt
      - --syncmode=full
    expose:
      - 8551:8551
      - 8545:8545
      - 6060:6060
      - 30303:30303
    volumes:
      - ./execution:/execution
      - ./execution/geth_password.txt:/execution/geth_password.txt
      - ./jwtsecret:/execution/jwtsecret

  # Runs a Prysm beacon chain from a specified genesis state created in the previous step
  # and connects to go-ethereum in the same network as the execution client.
  # The account used in go-ethereum is set as the suggested fee recipient for transactions
  # proposed via the validators attached to the beacon node.
  beacon-chain:
    image: "sigp/lighthouse"
    networks:
      ETHclient_net:
        ipv4_address: 172.19.0.12
    command:
      - lighthouse
      - b
      - --http
      - --datadir=/consensus/beacondata
      - --boot-nodes=${CL_BOOTNODE}
      - --execution-jwt-secret-key=/execution/jwtsecret
      - --graffiti=lighthouse
      - --testnet-dir=/consensus
      - --suggested-fee-recipient=0x123463a4b065722e99115d6c222f267d9cabb524
      - --execution-endpoint=http://172.19.0.11:8551
    depends_on:
      geth:
        condition: service_started
    expose:
        - 5052:5052/tcp
        - 5053:5053/tcp
        - 5054:5054/tcp     # metrics endpoint
        - 9000:9000/tcp
        - 9000:9000/udp
    volumes:
      - ./consensus:/consensus
      - ./jwtsecret:/execution/jwtsecret
  
  validator:
    image: "gcr.io/prysmaticlabs/prysm/validator:latest"
    networks:
      ETHclient_net:
        ipv4_address: 172.19.0.13
    command:
      - --beacon-rpc-provider=172.19.0.12:4000
      - --beacon-rpc-gateway-provider=172.19.0.12:3500
      - --graffiti=test 
      - --datadir=/consensus/validatordata
      - --accept-terms-of-use
      - --interop-num-validators=64
      - --interop-start-index=128
      - --chain-config-file=/consensus/config.yml
    depends_on:
      beacon-chain:
        condition: service_started
    volumes:
      - ./consensus:/consensus

networks:
  ETHclient_net:
    name: ETHclient_net
  