global:
  scrape_interval: 12s

scrape_configs:
  - job_name: 'docker_stats_exporter'
    static_configs:
      - targets: ["host.docker.internal:9487"]
  - job_name: "geth_normal"
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["host.docker.internal:6060"]
  - job_name: "prysm_normal"
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: "validator_normal"
    static_configs:
      - targets: ["host.docker.internal:8081"]
  - job_name: "geth_bugged"
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["host.docker.internal:6061"]
  - job_name: "prysm_bugged"
    static_configs:
      - targets: ["host.docker.internal:8090"]
  - job_name: "validator_bugged"
    static_configs:
      - targets: ["host.docker.internal:8091"]